#ifndef PINS_H_
#define PINS_H_

#define WHEEL_LEFT_PWN_PIN 10
#define WHEEL_LEFT_OUT_PIN_1 8
#define WHEEL_LEFT_OUT_PIN_2 9

#define WHEEL_RIGHT_PWN_PIN 12
#define WHEEL_RIGHT_OUT_PIN_1 2
#define WHEEL_RIGHT_OUT_PIN_2 3

#define WHEEL_ENCODER_RIGHT_PIN 0
#define WHEEL_ENCODER_LEFT_PIN 26

#endif